<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            ['name' => 'address.viewAny'],
            ['name' => 'address.viewAny.deleted'],
            ['name' => 'address.create'],
            ['name' => 'address.view'],
            ['name' => 'address.update'],
            ['name' => 'address.delete'],
            ['name' => 'address.restore'],
            ['name' => 'address.force.delete'],
            ['name' => 'cakeArrangement.viewAny'],
            ['name' => 'cakeArrangement.create'],
            ['name' => 'cakeArrangement.view'],
            ['name' => 'cakeArrangement.update'],
            ['name' => 'cakeArrangement.delete'],
            ['name' => 'chat.viewAny'],
            ['name' => 'chat.viewAny.deleted'],
            ['name' => 'chat.create'],
            ['name' => 'chat.view'],
            ['name' => 'chat.update'],
            ['name' => 'chat.delete'],
            ['name' => 'chat.force.delete'],
            ['name' => 'chat.restore'],
            ['name' => 'chatroom.viewAny'],
            ['name' => 'chatroom.viewAny.deleted'],
            ['name' => 'chatroom.create'],
            ['name' => 'chatroom.view'],
            ['name' => 'chatroom.update'],
            ['name' => 'chatroom.delete'],
            ['name' => 'chatroom.force.delete'],
            ['name' => 'chatroom.restore'],
            ['name' => 'city.viewAny'],
            ['name' => 'city.viewAny.deleted'],
            ['name' => 'city.create'],
            ['name' => 'city.view'],
            ['name' => 'city.update'],
            ['name' => 'city.delete'],
            ['name' => 'city.force.Delete'],
            ['name' => 'city.restore'],
            ['name' => 'idea.viewAny'],
            ['name' => 'idea.create'],
            ['name' => 'idea.view'],
            ['name' => 'idea.update'],
            ['name' => 'idea.delete'],
            ['name' => 'instrument.viewAny'],
            ['name' => 'instrument.viewAny.deleted'],
            ['name' => 'instrument.create'],
            ['name' => 'instrument.view'],
            ['name' => 'instrument.update'],
            ['name' => 'instrument.delete'],
            ['name' => 'instrument.force.delete'],
            ['name' => 'instrument.restore'],
            ['name' => 'message.viewAny'],
            ['name' => 'message.create'],
            ['name' => 'message.view'],
            ['name' => 'message.update'],
            ['name' => 'message.delete'],
            ['name' => 'notification.viewAny'],
            ['name' => 'notification.create'],
            ['name' => 'notification.view'],
            ['name' => 'notification.update'],
            ['name' => 'notification.delete'],
            ['name' => 'order.viewAny'],
            ['name' => 'order.deleted.viewAny'],
            ['name' => 'order.create'],
            ['name' => 'order.view'],
            ['name' => 'order.update'],
            ['name' => 'order.delete'],
            ['name' => 'order.force.delete'],
            ['name' => 'order.restore'],
            ['name' => 'permission.viewAny'],
            ['name' => 'practiceDate.viewAny'],
            ['name' => 'practiceDate.create'],
            ['name' => 'practiceDate.view'],
            ['name' => 'practiceDate.update'],
            ['name' => 'practiceDate.delete'],
            ['name' => 'product.viewAny'],
            ['name' => 'product.viewAny.deleted'],
            ['name' => 'product.create'],
            ['name' => 'product.view'],
            ['name' => 'product.update'],
            ['name' => 'product.delete'],
            ['name' => 'product.force.delete'],
            ['name' => 'product.restore'],
            ['name' => 'role.viewAny'],
            ['name' => 'role.viewAny.deleted'],
            ['name' => 'role.create'],
            ['name' => 'role.view'],
            ['name' => 'role.update'],
            ['name' => 'role.permission.update'],
            ['name' => 'role.delete'],
            ['name' => 'role.force.delete'],
            ['name' => 'role.restore'],
            ['name' => 'sheet.viewAny'],
            ['name' => 'sheet.viewAny.deleted'],
            ['name' => 'sheet.create'],
            ['name' => 'sheet.view'],
            ['name' => 'sheet.delete'],
            ['name' => 'sheet.force.delete'],
            ['name' => 'sheet.restore'],
            ['name' => 'team.viewAny'],
            ['name' => 'team.viewAny.deleted'],
            ['name' => 'team.create'],
            ['name' => 'team.view'],
            ['name' => 'team.update'],
            ['name' => 'team.user.update'],
            ['name' => 'team.delete'],
            ['name' => 'team.force.delete'],
            ['name' => 'team.restore'],
            ['name' => 'user.viewAny'],
            ['name' => 'user.viewAny.deleted'],
            ['name' => 'user.create'],
            ['name' => 'user.view'],
            ['name' => 'user.update'],
            ['name' => 'user.password.update'],
            ['name' => 'user.role.update'],
            ['name' => 'user.Instrument.update'],
            ['name' => 'user.delete'],
            ['name' => 'user.force.delete'],
            ['name' => 'user.restore'],
            ['name' => 'zipcode.viewAny'],
            ['name' => 'zipcode.view'],
        ];

        foreach ($items as $item){
            Permission::firstOrCreate($item);
        }
    }
}
